/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NovoEventoRouteImport } from './routes/novo-evento'
import { Route as NovoCartaoRouteImport } from './routes/novo-cartao'
import { Route as NovaListaRouteImport } from './routes/nova-lista'
import { Route as ListasRouteImport } from './routes/listas'
import { Route as GastosMesRouteImport } from './routes/gastos-mes'
import { Route as FluxoMensalRouteImport } from './routes/fluxo-mensal'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartaoIdRouteImport } from './routes/cartao.$id'
import { Route as ApiPublicProcessRemindersRouteImport } from './routes/api/public/process-reminders'

const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoEventoRoute = NovoEventoRouteImport.update({
  id: '/novo-evento',
  path: '/novo-evento',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoCartaoRoute = NovoCartaoRouteImport.update({
  id: '/novo-cartao',
  path: '/novo-cartao',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaListaRoute = NovaListaRouteImport.update({
  id: '/nova-lista',
  path: '/nova-lista',
  getParentRoute: () => rootRouteImport,
} as any)
const ListasRoute = ListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosMesRoute = GastosMesRouteImport.update({
  id: '/gastos-mes',
  path: '/gastos-mes',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoMensalRoute = FluxoMensalRouteImport.update({
  id: '/fluxo-mensal',
  path: '/fluxo-mensal',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoIdRoute = CartaoIdRouteImport.update({
  id: '/cartao/$id',
  path: '/cartao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessRemindersRoute =
  ApiPublicProcessRemindersRouteImport.update({
    id: '/api/public/process-reminders',
    path: '/api/public/process-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/financas': typeof FinancasRoute
  '/fluxo-mensal': typeof FluxoMensalRoute
  '/gastos-mes': typeof GastosMesRoute
  '/listas': typeof ListasRoute
  '/nova-lista': typeof NovaListaRoute
  '/novo-cartao': typeof NovoCartaoRoute
  '/novo-evento': typeof NovoEventoRoute
  '/perfil': typeof PerfilRoute
  '/semana': typeof SemanaRoute
  '/cartao/$id': typeof CartaoIdRoute
  '/api/public/process-reminders': typeof ApiPublicProcessRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/financas': typeof FinancasRoute
  '/fluxo-mensal': typeof FluxoMensalRoute
  '/gastos-mes': typeof GastosMesRoute
  '/listas': typeof ListasRoute
  '/nova-lista': typeof NovaListaRoute
  '/novo-cartao': typeof NovoCartaoRoute
  '/novo-evento': typeof NovoEventoRoute
  '/perfil': typeof PerfilRoute
  '/semana': typeof SemanaRoute
  '/cartao/$id': typeof CartaoIdRoute
  '/api/public/process-reminders': typeof ApiPublicProcessRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/financas': typeof FinancasRoute
  '/fluxo-mensal': typeof FluxoMensalRoute
  '/gastos-mes': typeof GastosMesRoute
  '/listas': typeof ListasRoute
  '/nova-lista': typeof NovaListaRoute
  '/novo-cartao': typeof NovoCartaoRoute
  '/novo-evento': typeof NovoEventoRoute
  '/perfil': typeof PerfilRoute
  '/semana': typeof SemanaRoute
  '/cartao/$id': typeof CartaoIdRoute
  '/api/public/process-reminders': typeof ApiPublicProcessRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/financas'
    | '/fluxo-mensal'
    | '/gastos-mes'
    | '/listas'
    | '/nova-lista'
    | '/novo-cartao'
    | '/novo-evento'
    | '/perfil'
    | '/semana'
    | '/cartao/$id'
    | '/api/public/process-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/financas'
    | '/fluxo-mensal'
    | '/gastos-mes'
    | '/listas'
    | '/nova-lista'
    | '/novo-cartao'
    | '/novo-evento'
    | '/perfil'
    | '/semana'
    | '/cartao/$id'
    | '/api/public/process-reminders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendario'
    | '/financas'
    | '/fluxo-mensal'
    | '/gastos-mes'
    | '/listas'
    | '/nova-lista'
    | '/novo-cartao'
    | '/novo-evento'
    | '/perfil'
    | '/semana'
    | '/cartao/$id'
    | '/api/public/process-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  FinancasRoute: typeof FinancasRoute
  FluxoMensalRoute: typeof FluxoMensalRoute
  GastosMesRoute: typeof GastosMesRoute
  ListasRoute: typeof ListasRoute
  NovaListaRoute: typeof NovaListaRoute
  NovoCartaoRoute: typeof NovoCartaoRoute
  NovoEventoRoute: typeof NovoEventoRoute
  PerfilRoute: typeof PerfilRoute
  SemanaRoute: typeof SemanaRoute
  CartaoIdRoute: typeof CartaoIdRoute
  ApiPublicProcessRemindersRoute: typeof ApiPublicProcessRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-evento': {
      id: '/novo-evento'
      path: '/novo-evento'
      fullPath: '/novo-evento'
      preLoaderRoute: typeof NovoEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-cartao': {
      id: '/novo-cartao'
      path: '/novo-cartao'
      fullPath: '/novo-cartao'
      preLoaderRoute: typeof NovoCartaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-lista': {
      id: '/nova-lista'
      path: '/nova-lista'
      fullPath: '/nova-lista'
      preLoaderRoute: typeof NovaListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listas': {
      id: '/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof ListasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-mes': {
      id: '/gastos-mes'
      path: '/gastos-mes'
      fullPath: '/gastos-mes'
      preLoaderRoute: typeof GastosMesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-mensal': {
      id: '/fluxo-mensal'
      path: '/fluxo-mensal'
      fullPath: '/fluxo-mensal'
      preLoaderRoute: typeof FluxoMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao/$id': {
      id: '/cartao/$id'
      path: '/cartao/$id'
      fullPath: '/cartao/$id'
      preLoaderRoute: typeof CartaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-reminders': {
      id: '/api/public/process-reminders'
      path: '/api/public/process-reminders'
      fullPath: '/api/public/process-reminders'
      preLoaderRoute: typeof ApiPublicProcessRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  FinancasRoute: FinancasRoute,
  FluxoMensalRoute: FluxoMensalRoute,
  GastosMesRoute: GastosMesRoute,
  ListasRoute: ListasRoute,
  NovaListaRoute: NovaListaRoute,
  NovoCartaoRoute: NovoCartaoRoute,
  NovoEventoRoute: NovoEventoRoute,
  PerfilRoute: PerfilRoute,
  SemanaRoute: SemanaRoute,
  CartaoIdRoute: CartaoIdRoute,
  ApiPublicProcessRemindersRoute: ApiPublicProcessRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
