/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NovoEventoRouteImport } from './routes/novo-evento'
import { Route as ListasRouteImport } from './routes/listas'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoEventoRoute = NovoEventoRouteImport.update({
  id: '/novo-evento',
  path: '/novo-evento',
  getParentRoute: () => rootRouteImport,
} as any)
const ListasRoute = ListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/financas': typeof FinancasRoute
  '/listas': typeof ListasRoute
  '/novo-evento': typeof NovoEventoRoute
  '/perfil': typeof PerfilRoute
  '/semana': typeof SemanaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/financas': typeof FinancasRoute
  '/listas': typeof ListasRoute
  '/novo-evento': typeof NovoEventoRoute
  '/perfil': typeof PerfilRoute
  '/semana': typeof SemanaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/financas': typeof FinancasRoute
  '/listas': typeof ListasRoute
  '/novo-evento': typeof NovoEventoRoute
  '/perfil': typeof PerfilRoute
  '/semana': typeof SemanaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/financas'
    | '/listas'
    | '/novo-evento'
    | '/perfil'
    | '/semana'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/financas'
    | '/listas'
    | '/novo-evento'
    | '/perfil'
    | '/semana'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendario'
    | '/financas'
    | '/listas'
    | '/novo-evento'
    | '/perfil'
    | '/semana'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  FinancasRoute: typeof FinancasRoute
  ListasRoute: typeof ListasRoute
  NovoEventoRoute: typeof NovoEventoRoute
  PerfilRoute: typeof PerfilRoute
  SemanaRoute: typeof SemanaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-evento': {
      id: '/novo-evento'
      path: '/novo-evento'
      fullPath: '/novo-evento'
      preLoaderRoute: typeof NovoEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listas': {
      id: '/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof ListasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  FinancasRoute: FinancasRoute,
  ListasRoute: ListasRoute,
  NovoEventoRoute: NovoEventoRoute,
  PerfilRoute: PerfilRoute,
  SemanaRoute: SemanaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
